version: "3.8"  # Рекомендуется использовать более новую версию

services:
  postgres:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - env
    environment:
      COMPOSE_HTTP_TIMEOUT: 3600
    ports:
      - 5432:5432
    networks:
      pgnet:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - .:/data
    environment:
      DEPLOYMENT: api
      COMPOSE_HTTP_TIMEOUT: 3600
      LC_CTYPE: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    env_file: env
    command: bash -c 'python3 myclinic/manage.py runserver 0.0.0.0:8000'
    networks:
      pgnet:

volumes:
  pgdata:

networks:
  pgnet:
